version: "3.1"

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - custom_network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
    ports:
      - 5601:5601
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - custom_network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.2.0
    container_name: logstash
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
    ports:
      - 5044:5044
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - custom_network

networks:
  custom_network:
    driver: bridge

volumes:
  esdata1:
    driver: local
